### ISSUE TITLE
Make Immersive Engineering Evacuator Fetch Infinite Ores 

### ISSUE THREAD

**Issue by dudeloony** [EnigmaticaModpacks/Enigmatica6#3350]
### Describe your suggestion

I think that it would be a good idea to change the immersive engineering ore deposits for the evacuator from finite to infinite in the default config.
(Also, I vaguely remember having a convo about this with someone else, but I couldn't find a similar "issue" on the issue tracker when searching for immersive engineering, so I think its original, but apologies if it's not.)

### Why would you like this added/changed?

I know there is a default config for Immersive Engineering, and I have altered that in my own world. I find that the limit on sample yield, although large, still stops me from using the IE evacuator instead of the IF lazer drill which is infinite and produces a wider range of ores or the Occultism demons, which have the same advantages. Although I don't have a problem with lesser-powered machines, I think expanding the use case for the evacuator would help balance it closer to its alternatives (Industrial Foregoing, Occultism, Bees). It's already a narrower yeild than the other two and costs more in resources and power, so I feel like making it infinite gives it a better use case (maybe uranium for reactors?) Although an argument could be made that Resourceful Bees already fits that niche and occupies a larger space on the quest book. I guess I'll leave it up to your intuition whether you think this is a good idea and worthwhile to implement or not.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'm not sure what my stance is on this tbh, I'll mow it over :)

**Comment by Thiana** [comment]
I like the idea of having it be infinite like the other methods. It would actually be worth building a mining complex around those specific deposits.

**Comment by MuteTiefling** [comment]
I do like the idea of it being infinite, but would rather it work more like IP's oil deposits do, where they start off strong and once you hit a threshold, they diminish to a low base rate. Perhaps just slow them down a lot and make them infinite anyway?

It's true that the other ore methods tend to outshine this, but they all have their strengths and weaknesses.

1) Bees: Require exploration and a lot of manual work to get all the bees one would desire. Requires a fair bit of logistics to process things properly as well. 
2) Botania/Nature's Aura: Each requires decent 'energy' generation for their respective sources.
3) Industrial Foregoing: Infinite, but slow without spending a lot of resources on extra lasers. Requires a fair amount of work to reach. Could honestly stand to be more expensive, power wise, however. 
4) IE: really not that expensive in terms of power (4k/t), but requires a fair bit of work to actually find nodes. Machine is moderately costly to craft, but very easy to place thanks to Building Gadgets. 
5) Builder Quarry: Not infinite, but running it once on max range does tend to get you more materials than you're likely to ever use...

That last one, is important too. While some of these are legitimately infinite, the IE Excavator is, in many cases, functionally infinite since you'll get more from one node than you're likely to need for anything.

**Comment by dudeloony** [comment]
I like the idea of it being more like IP's oil veins, personally.

**Comment by NillerMedDild** [comment]
This suggestion could stand some stats 😄 what are the rates like at the moment, do we have a table for that or something? ^^'

**Comment by MuteTiefling** [comment]
Not so much no :D 30-40k ores per mineral node. Multiply by whatever you're getting from your current ore processing infrastructure. They're pretty generous.

**Comment by NillerMedDild** [comment]
Oh the yield actually depletes over time, I'm for increasing this to something silly.

![image](https://user-images.githubusercontent.com/21295394/141697855-95e0c425-fa8e-4194-aa04-21c98e44705f.png)

**Comment by NillerMedDild** [comment]
@dudeloony see above commit for proposed changes, what do you think?

**Comment by dudeloony** [comment]
Well, I'm a little late, but I think its great personally. Thank you for making this change!
