### ISSUE TITLE
Mekanism Jetpack Sound 

### ISSUE THREAD

**Issue by FooterMan14** [EnigmaticaModpacks/Enigmatica6#3804]
### Modpack Version

0.5.21

### Describe your issue.

It appears when you change any sound level (master. music, players, etc) the Mekanism jetpack stops making noise. I found this issue on a server, and I have tested on singleplayer with this issue never happening. I assume it is a mod bug.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by pupnewfster** [comment]
I started looking into this a little, and other than the weird thing of when fully muting player sounds and then unmuting it the jetpack sound not being able to be started again at all I am not able to reproduce this. Is this all you meant or something else because just lowering the sound of another category doesn't stop it at all.

**Comment by FooterMan14** [comment]
For me when I lowered any category the jetpack sound would completely stop, and the only way I was able to fix it was by re-logging into the server.

**Comment by FooterMan14** [comment]
I found no other ways to re-produce

**Comment by pupnewfster** [comment]
@NillerMedDild @FooterMan14 could one of you try reproducing with just mekanism (and accompanying mods or not) and seeing if you can reproduce the issue? Because if not I feel like it is likely that there is some coremod in the pack that is screwing with how the sound system works. Either way I will try to fix the issue I found while trying to reproduce this, but I think it is most likely unrelated to this (unless it happens to be one of the issues I fixed earlier in the year in the 10.1 branch, given I am testing using the 10.1 branch)

**Comment by FooterMan14** [comment]
If I had to guess the mod breaking the sound is the one that allows you to change where the sound goes

**Comment by Darkere** [comment]
Cannot reproduce with a (much) smaller pack.
