### ISSUE TITLE
Enigmatica 6 Expert Astral sorcery Iridescent Altar

### ISSUE THREAD

**Issue by Kevin-Marsh** [EnigmaticaModpacks/Enigmatica6#4010]
### Modpack Version

Dev

### Describe your issue.

I am trying to get into Astral Sorcery and can't make an Iridescent Altar. I have tried both the default placing the crafting table under the crystal in the temple (which is what is outlined in the quest) and the JEI recipe Magic workbench. The Crafting table lights up but doesn't progress into the Altar and the Magic Workbench doesn't do anything.

EDIT: I mean the Luminous Crafting table not the altar 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Rodg88** [comment]
Have you used a linking wand from AS to link the crystal to the magic workbench?

**Comment by Kevin-Marsh** [comment]
Well, that all makes sense now. I just double checked the quests and all of what I wrote is a known issue and indeed you need the linking tool. I was following the astral sorcery quest line not the Magic - Apprentice line. Maybe the Astral sorcery quests need to be updated to show the same line in the beginning as the magic apprentice quests.

**Comment by MuteTiefling** [comment]
Unfortunately the main 'mod' quests are used by both Expert and Normal. This makes it hard to make things clear for all users. That's why the Expert quests exist, to guide you through the altered progression of the mods, while the standard quests guide normal mode players through standard progression.

I'm honestly not really sure how else to resolve this one without causing further confusion... I suppose a simple note at the bottom of the Luminous Crafting Table quest?

**Comment by Kevin-Marsh** [comment]
I think a brief note at the bottom of the luminous crafting quest would probably work. Just something to say that there is a second luminous crafting quest in the magic apprentice section for expert players. Would it also work to title them separately? Just call the one in the Astral sorcery section Luminous Crafting Table -Normal Mode and the one in the apprentice section Luminous Crafting Table - Expert mode?

**Comment by MuteTiefling** [comment]
Fixed in dev
