### ISSUE TITLE
When i press shift on a backpack to view its contents, this happens.

### ISSUE THREAD

**Issue by HopeNotDespair** [EnigmaticaModpacks/Enigmatica6#4105]
### Modpack Version

0.5.23(Beta) 

### Describe your issue.

![2022-01-22_14 54 15](https://user-images.githubusercontent.com/96193806/150632961-53886778-79f8-4ad0-b609-93928beb4263.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Seems to be an issue with Equipment Compare, I thought we blacklisted backpacks from it though.

**Comment by SeooY** [comment]
I can confirm this started happening when I updated to 0.5.25.

**Comment by HopeNotDespair** [comment]
Yes, I updated to 0.25 as well, but it still persists. Could you please take a look at the blacklist again?

**Comment by Rodg88** [comment]
The blacklist hasn't changed in 2 months, but you could check that your copy of /config/equipmentcompare-common.toml matches the github version here: https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/config/equipmentcompare-common.toml

**Comment by HopeNotDespair** [comment]
But, then why is it still working?

**Comment by MuteTiefling** [comment]
I can't reproduce this in my dev instance. Will try in my release instance in a bit, but I suspect the error is on your side.

**Comment by SeooY** [comment]
I just downloaded a brand new copy of 0.5.25 from CurseForge and there's no default config for Equipment Compare in the zip, I assume that the default is being generated at the start of the game. When I updated I had to create a new profile so that could be the reason, if you have the config from an older version then it's fine, but if you install a new profile from scratch currently then the config with the blacklist is not there.

**Comment by SeooY** [comment]
I just downloaded a brand new copy of 0.5.25 from CurseForge and there's no default config for Equipment Compare in the instance, I assume that the default is being generated at the start of the game. When I updated I had to create a new profile so that could be the reason, if you have the config from an older version then it's fine, but if you install a new profile from scratch currently then the config with the blacklist is not there.

**Comment by HopeNotDespair** [comment]
Try it when you are wearing a backpack @MuteTiefling

**Comment by theboo** [comment]
somehow the config did not get shipped with the pack in release, wouldn't show up in dev... as a temp fix you can copy the blacklist from https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/config/equipmentcompare-common.toml and put it in the config in your instance until the next release
