### ISSUE TITLE
Ingot/Plate/Rod Textures

### ISSUE THREAD

**Issue by Quantombb** [EnigmaticaModpacks/Enigmatica6#4273]
### Describe your suggestion

Just some general feedback on the ingot/plate/rod textures

Brass and Zinc are really green, the Create Zinc and Brass textures were perfectly fine and did not have to be replaced.
Constantan, Arcane Gold, and Copper look too similar.
Compressed Iron and Steel look similar.
All the plates are too large and look darkened. (Create-Style Plates would look better imo)
All the ingots are the same shape, making it hard to differentiate between them.
The rods have a really thick black outline that looks weird.

### Why would you like this added/changed?

It is easier to look at, and would be a welcome addition to this pack.

**Comment by MuteTiefling** [comment]
All of our textures for these were made custom to unify the items across the various mods. They're made to emulate the 1.16 art style.

Ingots are all the same shape. That's what an ingot is, after all. They can be differentiated by color.

The darkness on rods gives them the illusion of being rounded.

**Comment by jlfree12** [comment]
Imagine insulting Rid’s textures. They are literally the best textures in all of modded.

**Comment by tuca1234567890** [comment]
> Imagine insulting Rid’s textures. They are literally the best textures in all of modded.

let the man have opinions 😔

**Comment by Ridanisaurus** [comment]
You are 110% entitles to have a personal opinion on the textures, and the beauty of MC is that if you don't like how something looks, just make a Resource Pack and change it to your liking.
Personally, I hate the way Create Zincs look because it doesn't look like a standard ingot, and the plates are too wiggly for my liking. Everyone have an opinion, and that's perfectly fine, it's what makes us so fucking beautiful as species.
You simply can't please everyone, and that's okay. Just make a Resource Pack that makes you happy.
