### ISSUE TITLE
[expert] Foundation and Building Materials for medium machinery unlock is Much too expensive

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [EnigmaticaModpacks/Enigmatica6#4284]
### Describe your suggestion

For unlocking the medium machinery blueprints of immersive engineering, having to do 500 sequenced assemblies for building and foundation materials seems excessive for that point in the game. 

### Why would you like this added/changed?

Not 500 sequenced assemblies? 300 is my opinion.

**Comment by TemperedFool** [comment]
I think the difference between 300 and 500 is basically irrelevant, and once you have the materials loaded it doesn't really take that long to produce them. I think this serves an important role in letting the player know they need to scale up their automation - turning it down too much would reduce that impact. Plus 500 seems like a nicer rounder number than 300.

**Comment by MuteTiefling** [comment]
Beyond what Tempered said, understand these numbers weren't an arbitrary choice: You're buildinga school meant to house 20 people, and the values were calculated to represent that imaginary structure. 

I've forgotten the exact dimensions I was aiming for, but it was a large building. Treated wood would make up the walls, glass for windows, scaffolding for general support, copper shingles for the roof, and a thick floor/foundation of concrete with bricks visible on the outside. Turf to pretty things up outside, leaves for bushes, flowers, etc. 

It's really no different than someone deciding to set out and build a large base. The difference is you're doing all the material prep up front, as opposed to doing a bit at a time as sometimes happens. We tend to forget how much material goes into a large build, but thousands of blocks is not unheard of. 

With the way sequenced assembly works, you can easily run all five of the required building materials boxes in sequence on the same line. At high speed, this takes about 20 minutes to do all 5. Incidentally, it takes 20 minutes to do one by itself too, but that's part of the Expert challenge: realizing you can save time here by doing them together and running them all in parallel. 

I intentioinally kept this to relatively cheap materials for this reason. It will still require you to set up some automation, however, as most people haven't accumulated enough creosote by that point, even if they've been storing every bucket they've made. Concrete is similarly cheap, but requires you to set up some automation to produce in quantity here, and that's the real lesson here: Start Automating. Because by the time you get to end game, you'll absolutely need this and other stuff in large quantities.
