### ISSUE TITLE
Can't start server of E6:E 1.0.0 , that use world from expert mode 0.5.26

### ISSUE THREAD

**Issue by AlphaP2712** [EnigmaticaModpacks/Enigmatica6#4379]
### Modpack Version

1.0.0

### Describe your issue.

 I have problem to start server of E6:E 1.0.0 , that use world that create in expert mode 0.5.25 and update to 0.5.26 before try to update to 1.0.0. Server stop to do any thing after prepare world spawn phase
here is log file
[latest.log](https://github.com/EnigmaticaModpacks/Enigmatica6/files/8232653/latest.log)
 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by AlphaP2712** [comment]
additional infomation , 0.5.27 is not working too.

**Comment by AlphaP2712** [comment]
https://drive.google.com/file/d/1R5ooQD-rqhHj6b2QI5jNc_QVQrdwKVQN/view?usp=sharing here is my world folder

**Comment by NillerMedDild** [comment]
Would you mind sharing your `debug.log`?

**Comment by AlphaP2712** [comment]
absolutely sure
[debug.log](https://github.com/EnigmaticaModpacks/Enigmatica6/files/8234356/debug.log)

**Comment by NillerMedDild** [comment]
Huh, not much to work with in the `debug.log` either :/ I have no idea what's going on here tbh.

**Comment by AlphaP2712** [comment]
It seem like problem start on 0.5.26 to 0.5.27 ,Is something that change between that 2 version cause a problem?

**Comment by NillerMedDild** [comment]
Not as far as we know, upgrading our own servers went just fine :/

**Comment by oitsjustjose** [comment]
Not that saying "I have the same problem" helps, but I too have the same exact issue with a singleplayer world refusing to load in the 0.5.27 update or newer. 0.5.26 works just fine. My `debug.log` and `latest.log` don't have any sort of failures in them either, same as Alpha. I don't see any suspect mods in the .27 update except for `Ars Creo`, since it's supposedly GNU GPL but doesn't have comments, an issues page or a Repo anywhere so it's impossible to tell. I'll start by removing that and come back..

Until then, I would be glad to provide my full save if that would be of any assistance.

**Comment by oitsjustjose** [comment]
Removing the following 4 (from the changes in `.27`) seem to have fixed this: 

![image](https://user-images.githubusercontent.com/3887324/159083725-4743b586-2b7c-4c83-9fb5-f69d7d778153.png)

I will start re-enabling those that didn't fix it before and let you know which one it comes down to.

**Comment by oitsjustjose** [comment]
It's Starlight. I was under the impression this was supposed to be removed, but I may be mistaken!

**Comment by theboo** [comment]
> It's Starlight. I was under the impression this was supposed to be removed, but I may be mistaken!

correct, it was supposed to be removed, but made it in to 1.0.0 by accident

**Comment by NillerMedDild** [comment]
Thanks for ttracking down the cause :D
