### ISSUE TITLE
Spawn is a floating island

### ISSUE THREAD

**Issue by eliminat** [EnigmaticaModpacks/Enigmatica6#4383]
### Modpack Version

1.0.0

### Describe your issue.

Not sure how major of an issue this is, but it doesn't seem ideal.
Spawned into Expert - spawn is on a floating island. (specifically a "Clay Island")
![2022-03-12_00 16 07](https://user-images.githubusercontent.com/7636368/157994771-3f7af016-51c8-4e15-a1ae-f58c6a4ed30a.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by eliminat** [comment]
Update: Seems it was only for the first logon.
2nd player joining joined on the ground.

**Comment by User-12691296** [comment]
Vanilla has a default mechanic, SpawnRadius. It's a gamerule that makes players that join spawn randomly in a (default 10 block) radius from the world spawn. 

When the game spawns you in, the SpawnRadius+SpawnPoint declare the x and z of your spawn point, and the highest valid spawn block (dirt, grass, stone, sand, not underwater, and a couple other restrictions) will determine the y of your spawn point.

This is not actually a bug, it's just a quirky feature that happened because of the juxtaposition of that island and the spawnpoint. Similar things can happen in vanilla

If you don't want that, run the /spawnpoint command to push the world spawn farther out, so spawning will not happen on the skysland.

However, there is water under you, so it's not a big deal. You'd be perfectly fine to just practice your air moving skills. Turn off view bobbing and look straight down, and you're set for a 100% landing in the water chance.
