### ISSUE TITLE
Partial coke & blast bricks can be placed, wiping NBT

### ISSUE THREAD

**Issue by Officialy** [EnigmaticaModpacks/Enigmatica6#4423]
### Modpack Version

1.0.0

### Describe your issue.

Upon placing a partial coke brick or blast brick, you wipe the NBT data required for the Sequenced assembly to work/continue working upon them. A solution to this would be to make it an item, with the same block model. Making it look the same, however just not placeable.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by MuteTiefling** [comment]
I'm on the fence here. Honestly, I'd rather see this setup be automated, so you're not manually moving the block around.

I agree it sucks losing that progress though.

**Comment by TemperedFool** [comment]
I'm wondering why placing them wipes the NBT - is that normal?

Honestly I think we should just make them items, rather than blocks - I agree we want players to automate, but there's also not really any reason for people to place them?

I think we can even tag them with `create:upright_on_belt` to get them to sit up on belts even. I can test later.

**Comment by MuteTiefling** [comment]
most blocks that retain their NBT on placement/pickup are tile entities with special handling by the mod. a simple block doesn't have anywhere to store that nbt and retrieve it when it's picked up.

**Comment by TemperedFool** [comment]
Makes sense. I'll test swapping them to items, see if it breaks anything; I don't see why it would tbh.
