### ISSUE TITLE
1.1.2 server downloads all the mods from 1.0.0

### ISSUE THREAD

**Issue by Porcy** [EnigmaticaModpacks/Enigmatica6#4553]
### Modpack Version

1.1.2

### Describe your issue.

Downloaded the 1.1.2 zip pack. Created a new folder for it. Start the server. Downloads everything. All mods versions are the same as in 1.0.0. My 1.1.2 client can't connect.

### Have you modified the modpack?

Yes

### User Modifications

Removed bh_menu

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
I can't reproduce this, please re-download and try again :)

**Comment by mcdodge34** [comment]
I'm the brother of the one that actually did the report, I tested this on my own PC and everything works like expected, I'm now thinking he must have screwed with something on his side, cause I did a test run with both a client and server in 1.1.2 checked to make sure the files were different from 1.0.0 and they were clearly updated, maybe something on his side, will discuss that with him later today, could it be because he created a subfolder inside the original server that the program would start the wrong server, this is what I'm thinking, he may have loaded the 1.0.0 because of a script issue in your .bat that loaded the previous one. Will try to make a whole backup and only keep the 1.1.2 server files on the disk and we will see what happens.

**Comment by Porcy** [comment]
Stupid user here. Copied old server-setup-config.yaml into the new server folder to keep the forcedJavaPath: line from 1.0.0

**Comment by User-12691296** [comment]
While not the exact same thing, I had a similar problem using git pull to update my instance. The mods are not in the github, so they don't update when you run git pull. You also have to run InstanceSync.jar after every update done with that method

**Comment by NillerMedDild** [comment]
> While not the exact same thing, I had a similar problem using git pull to update my instance. The mods are not in the github, so they don't update when you run git pull. You also have to run InstanceSync.jar after every update done with that method

You need to run InstanceSyncSetup, that ensures InstanceSink updates mods whenever you pull.
