### ISSUE TITLE
incorrect building gadget template

### ISSUE THREAD

**Issue by Toonlink264** [EnigmaticaModpacks/Enigmatica6#4606]
### Modpack Version

Expert 1.1.2

### Describe your issue.

the template for the automated engineers workbench was incorrect. needed to mirror the copy and the belts were backwards 
(reference for motoko)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Toonlink264** [comment]
had to mirror the diesel generator as well

**Comment by MuteTiefling** [comment]
I've fixed the Workbench since the direction of the belts was legitimately breaking it. These structures, however, can bee freely mirrored/rotated. So the fact that the Diesel Generator Pattern comes in mirrored compared to the IP Projector doesn't matter; it still formed for me just now mirrored or not.
