### ISSUE TITLE
-0.99 1x1 internal vollume pressure chamber cannot take 16 books

### ISSUE THREAD

**Issue by Quezler** [EnigmaticaModpacks/Enigmatica6#4630]
### Modpack Version

1.1.2

### Describe your issue.

If you insert books in bulk to extract enchantments they can get stuck in the input interface with the warning that there is not enough pressure for them to insert those 16 (issue possibly occurs with less too) unenchanted vanilla books, and you cannot add "more" negative pressure beyond -0.99 & you cannot grab items by hand from out of the interface, landing you at a stalemate.

pneumaticraft mod issue 👀  

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by MuteTiefling** [comment]
You need volume upgrades to be able to transfer that many books at once. It takes a certain amount of air (positive or negative) per item to transfer, basically. 

If you have some volume upgrades lying around, toss em in. Otherwise, you'll have to break the structure to get them out. You can preserve your air by Sneak Right Clicking the Pressure Chamber Valve with a PNC Wrench.

**Comment by jamaa** [comment]
@Quezler did you manage to get it to work with volume upgrades? I am having the same issue in E9E, but even 16 volume upgrades does nothing.

**Comment by Quezler** [comment]
hmm its been a while so i'm not sure how i solved it exactly, i might have just put less items at once in there, its honestly too long to remember and the world/server is kinda gone.
