### ISSUE TITLE
Using old version of BetterEnd - Crashing with Forge Sodium.

### ISSUE THREAD

**Issue by viceversagames** [EnigmaticaModpacks/Enigmatica6#4650]
### Modpack Version

Enigmatica 6 Expert 1.1.2

### Describe your issue.

The version of BetterEnd shipped with this pack is out of date and causes a crash when adding Forge Sodium ports to the pack, which otherwise work fine. I noticed you didn't fix it in https://github.com/EnigmaticaModpacks/Enigmatica6/issues/3878, so I'm making another request to update it as Forge Sodium (Magnesium, Rubidium) actually runs really well in this modpack.

someoneelse (the developer for Magnesium) forked the mod and added compatibility for Forge Sodium ports as well as some other unrelated fixes and updates from the Fabric version. This version is also unmaintained, but it's better than what you have, and is the version used by Better Minecraft:

https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked

If you check the Github for the official BetterEndForge, it's been pull requested with the changes by someoneelse, but for some reason an update hasn't been pushed to CurseForge. No idea why, but if the official BetterEndForge gets any updates, it will include these changes.

https://github.com/Beethoven92/BetterEndForge

I've replaced it on my server with no issues. 

### Have you modified the modpack?

Yes

### User Modifications

Added Magnesium, Magnesium Extras & Dynamic Lights, and Calcium. Modpack runs great with the additions, but the out-of-date version of BetterEnd causes a crash unless it's updated manually.

### Did the issue happen in singleplayer or on a server?

Both

**Comment by viceversagames** [comment]
On an unrelated note, you mentioned you don't trust Forge Sodium, but it is much more stable than it was months ago, and in my opinion much better than Optifine. Magnesium is feature-complete and runs well in most packs. Only has minor visual bugs for a few things, many of which are fixed by Calcium's compatibility addons. 

I haven't tested Rubidium as much, but the dev is active and competent.

It's currently shipping with Better Minecraft Forge, including my own Magnesium Extras & Dynamic Lights mods, and been very stable. I've been playing with it in my own packs and Enigmatica and have not had any issues---and in the event one comes up, it can always be disabled.

**Comment by NillerMedDild** [comment]
To be honest I don't have time to verify that these performance mods work well in Enigmatica. I thought Starlight worked great, but that turned out to crash maaany servers. Adding performance mods is risky, we need tons of verification work before we can use them.

I'll update BetterEnd for the benefit of those who wish to use Magnesium :)

**Comment by SweptWasTaken** [comment]
This isn't specifically for you Niller, since it's not your job to diagnose this stuff. More for @viceversagames and anyone else modifying their modpacks with these performance mods.

I'm using AdoptOpenJDK Java 11, Enigmatica 6 Expert, the recommended Java arguments and Better End Reforked. I tested this by loading into a Singleplayer world, then loading into my Dedicated server.

[Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Lazy DFU](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge) = Works

[Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) = No Shaderpacks setting outside of game, crashes when loading in.

[Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Calcium](https://www.curseforge.com/minecraft/mc-mods/calcium) + [Lazy DFU](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge) = Crashes FTBLib on load.

[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) = Works, but is unstable, at least when joining my server.

[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) = Worked for a bit, but unstable and inconsistent. Crashed when trying to load Complementary Shaders v4.4 while in-game.

[Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Lazy DFU](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge) = Works, but is unstable, at least when joining my server.

I would like to try [Calcium](https://www.curseforge.com/minecraft/mc-mods/calcium/files) with Rubidium but it is not currently compatible due to a mistake on Calcium's side.

I tried using [KryptonReforged](https://www.curseforge.com/minecraft/mc-mods/krypton-reforged) and it functions fine in Singleplayer, but when loading into my server it loads into an error, saying something about the packet size being too large.

**Comment by viceversagames** [comment]
@SweptWasTaken 

> I'm using AdoptOpenJDK Java 11

AFAIK Java 11 can cause extra issues on 1.16.5. I stick to Java 8.

> [Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) = No Shaderpacks setting outside of game, crashes when loading in.

Oculus doesn't work with Magnesium, only versions of Sodium that support Iris rendering, like Rubidium.

> [Magnesium](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) + [Calcium](https://www.curseforge.com/minecraft/mc-mods/calcium) + [Lazy DFU](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge) = Crashes FTBLib on load.

I don't think Lazy DFU has anything to do with that. Probably an issue with Calcium and Java 11?

> [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) + [Magnesium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) = Works, but is unstable, at least when joining my server.

Yeah, Rubidium is newer.

> I tried using [KryptonReforged](https://www.curseforge.com/minecraft/mc-mods/krypton-reforged) and it functions fine in Singleplayer, but when loading into my server it loads into an error, saying something about the packet size being too large.

I've had a few reports of this error, but I can't seem to replicate the root cause. Do you still get it with Java 8?

**Comment by SweptWasTaken** [comment]
@viceversagames 


> I don't think Lazy DFU has anything to do with that. Probably an issue with Calcium and Java 11?

Yeah, switching to Java 8 fixes this, I loaded into my server fine.

> I've had a few reports of this error, but I can't seem to replicate the root cause. Do you still get it with Java 8?

Yep

![image](https://user-images.githubusercontent.com/49448379/163692339-834fc77c-93e5-42f2-9fed-f053cc7a6d3f.png)

**Comment by viceversagames** [comment]
Strange. I'll have to debug that error more, but unfortunately, I'm just the guy who's porting it, the Fabric dev wants nothing to do with Forge as per usual.

**Comment by SweptWasTaken** [comment]
@viceversagames On my server I get this when running Mag + Mag Extra + LazyDFU + Calcium. If I break any of the invisible blocks, it crashes my game. (Not the server.)

![image](https://user-images.githubusercontent.com/49448379/163693698-aaac3bb2-328f-4601-a124-ffefa6e4678e.png)

https://paste.ee/p/sidzJ

**Comment by viceversagames** [comment]
You're running Oculus.

**Comment by SweptWasTaken** [comment]
> You're running Oculus.

Sorry, copy-pasted the wrong log. I'm not running Oculus.

**Comment by viceversagames** [comment]
then paste the correct log

**Comment by SweptWasTaken** [comment]
> then paste the correct log

Edited my previous comment, [paste.ee/p/9s5PW](https://paste.ee/p/9s5PW)

**Comment by viceversagames** [comment]
Are you using the correct version of BetterEnd on the server side?

**Comment by SweptWasTaken** [comment]
> Are you using the correct version of BetterEnd on the server side?

Yep

`[16Apr2022 21:51:05.301] [main/DEBUG] [net.minecraftforge.fml.loading.moddiscovery.ModFileInfo/LOADING]: Found valid mod file betterendforge-1.16.5-2.5.jar with {betterendforge} mods - versions {1.16.5-2.5}`

**Comment by SweptWasTaken** [comment]
> Are you using the correct version of BetterEnd on the server side?

Hmm appears the mod "Better Biome Blend" is incompatible with Sodium. https://www.curseforge.com/minecraft/mc-mods/better-biome-blend

**Comment by SweptWasTaken** [comment]
Nvm, removed Better Biome Blend and I still have the same issue.

**Comment by SweptWasTaken** [comment]
Turns out the invisible blocks glitch is caused by Calcium.
