### ISSUE TITLE
Make altar of birthing locked to another dimension in e6 expert

### ISSUE THREAD

**Issue by thatGuyCalledMax** [EnigmaticaModpacks/Enigmatica6#4692]
### Describe your suggestion

To lock the altar of birthing to another dimension, such as the end until after a post masticator gamestage (maybe spirit of calling?), similar to occultism/BM. 

### Why would you like this added/changed?

This would mean that people will be much less likely to wipe their bees/villigers/drygmys/whatever when summoning the masticator (especially when they dont read the warnings). If this is in the end you would then see all the endermen dying which (may?) show how the breathless effect works, helping people understand the aura system better. Also thematic with the locking magic mods to other dimensions theme.

**Comment by thatGuyCalledMax** [comment]
(Idc if this passes to much, but seemed like a cool idea i had that would help with one of the major complaints i see most days on the discord)

**Comment by NillerMedDild** [comment]
Interesting idea, I quite like it. @MuteTiefling what do you think?

**Comment by tyler489** [comment]
I like the idea, but not the end, I have a feeling more than one server will have a "trapped" end spawn because of it, where as soon as you sign in you die because someone put the birthing alter to close to the portal

**Comment by MuteTiefling** [comment]
So, one word Thai keeps getting tossed about here is punitive. Punishment was never the intention here.

What I was aiming for here is the same as what I've done with Atum, Undergarden, and the various boss fights you're pushed into early on. It's the same reason enchants are difficult to come by and armor can't be crafted very easily.

Risk. 

If you go into Atum to fight a pharaoh without doing some preparation and exploring first, you'll very likely die. Repeatedly.

Same for Undergarden's catacombs or fighting the Wilden Chimera. Heck, the Wither has been in the game for ages and still causes some people grief as they fail to prepare for it. 

I guess the difference here is that people, in general, understand how to prepare for a fight they can see. And this isn't visible. 

But this isn't exactly the only unseen danger either. Lightning can strike and kill your farm animals, burn your house down, or convert your villagers to witches. 

Zombies can come eat your villagers. 

Your fission reactor can explode, killing everything in a larger area with absolutely no way to fix it afterwards. Just wait it out. 

Aura can severely damage the area and kill mobs. This can happen so slowly your don't even notice it normally since a lot of the aura draws are otherwise quite slow. 


The thing is, all of these are entirely avoidable.

In the case of aura, the player can already opt to do this far away or in another dimension. Or they can, as intended, set up aura gen in their base and very safely summon it there. I did so with no loss of bees or villagers. I've seen others do so as well. 

So I don't think forcing the player to only do this in another dimension is the right move. That feels like a level of hand holding that, at that point, we may as well remove the danger of our entirely. There's no risk, since there's absolutely nothing of value in those dimensions that will be lost by messing this up. And we've already largely removed the risk in the overworld by making bees drop an item to recover them. 


One thing that came of my discussion with @MaxNeedsSnacks earlier is them mentioning there's no need to even generate aura before this, much less automatically. Asks no reason to craft the environmental eye, which shows your what's happening. So despite the warnings that this is dangerous, there's also no natural pressure to prepare. It's not like combat where you're already being threatened by weaker mobs before facing off against a boss. 

So, if we are going to use game stages to 'fix' this, I'd instead propose that we force creating an aura generator and an environmental eye first. You can't even place the altar if you haven't done so. 

But this feels unnatural and forced as well. Unlike what we've done with dimensions, the gamestage here isn't a reward, it's a padded suit. It feels more condescending than anything. 

So maybe what's actually needed here are some expensive aura crafts leading up to this. Things that would cause aura to drain sufficiently that you'd need to start generating, fast enough that you'd notice it, but slow enough that it's not the same threat as the masticator summon. 

I think a couple early game crafts could be moved over to the natural altar. They could be given a high cost, but the natural altar never goes negative, so it would be a very clear indication that something is wrong and needs fixing prior to getting to the masticator itself.

**Comment by SCLeoX** [comment]
@MuteTiefling 

I think another great way of adding risks to the pack would be introducing a special explosion crafting recipe for some essential progression item. This recipe should look exact the same in JEI as others with absolutely no indication of danger. When triggered with a TNT however, instead of a regular explosion, it will cause a explosion of the a similar magnitude as a draconic reactor explosion that is not protected by FTB chunks. Also, to be very clear, this is never meant to punish the player. It is just used to add some risks. (And a healthy reminder to the player that this is a expert pack and whatever they previous know about TNTs are obsolete and they better spend 10 minutes before every single explosion craft to log in to a creative world to test in order to mitigate the risks.)

Sorry for the satire, I can't help it. That said, I honestly thought this was a bug with the pack which caused the aura to be drained repeatedly. When it occurred to my friend and I (it killed 16 * 9 = 144 bees and 2 little logistics boats), we just shrugged it off and loaded a backup. To be very clear, we enjoyed this pack a lot, and are continuing to enjoy it after this incident. It wasn't a big deal to us since we were playing on a private server. But I do find your argument a bit absurd, and I think somehow removing this risk would really benefit future players, allowing them to have a better experience.

**Comment by noa12390** [comment]
there would be a second reason to not lock this to the end or nether most servers reset them on a monthly basis because players will strip them off nearly all ores in a month at least

**Comment by CoteRL** [comment]
I'd think even just a real warning that the summon drains enough aura to cause mob death in the area and to either prepare by generating a lot of aura beforehand or by placing the altar far away. The text currently doesn't stress that it needs to be VERY far away to not still cause mayhem in your base.

**Comment by MuteTiefling** [comment]
The quest doesn't stress distance because distance isn't the intended way of dealing with it; Aura Automation is.
