### ISSUE TITLE
Improve Discoverability of Amadron Survey Tools

### ISSUE THREAD

**Issue by fistsh** [EnigmaticaModpacks/Enigmatica6#4700]
### Describe your suggestion

The **Amadron Survey Tools** item seems like a very cool way to trade for certain rare / annoying-to-get resources without needing to spend ages mining for them. However, I am fairly certain I don't speak just for myself when I say that **I likely would never have discovered them** if I hadn't been directly told of their existence by an Enigmatica 6 developer.

The existence of this item and its usefulness could be increased by doing any/all of the following, among other things:

- Increase quantity/consistency of references to it in the quests: As explained below, only relying on the description of one specific quest to impart information like this is insufficient, particularly in Expert mode.
  - Have both Amadron quests refer to the Enigmatica-specific trades, instead of just the one quest.
  - Potentially even add this info to other, related quests (e.g. in Adventure -> Godforged Blocks, "If you need more Nebu, check out the Amadron tablet trades!" ??)
- Add a Tooltip (lore) line to the Amadron Survey Tools, describing their use to obtain a cache of other-dimensional resources. IIRC, this can be done with something like as follows:
  
  In a KubeJS startup script (probably `minecraft\kubejs\startup_scripts\item_registry.js`, though **some refactoring seems necessary** to allow for this):
  `event.create('amadron_survey_tools') /* etc. */ .tooltip(NBT.toTag('{"translate":"item.kubejs.amadron_survey_tools.tooltip","color":"aqua"}'));`
  
  And in the lang files (e.g. `minecraft\kubejs\assets\kubejs\lang\en_us.json`), a line like this:
  `"item.kubejs.amadron_survey_tools.tooltip": "Used to trade for a variety of materials from other dimensions!",`

### Why would you like this added/changed?

- The Amadron Survey Tools are primarily discoverable by players in the manner of reading the description of the Amadron quest - and **not the Expert Amadron quest**, but the one under the PNC questline. However, this is not an ideal way of imparting information to players - there are literally hundreds of quests in Enigmatica, and more in Expert mode, and players will not want to stop and fully read each and every task description on the _off chance_ that there's something modpack-specific there.
  - This goes double for Expert mode, where a lot of trades have an Expert-questline duplicate, and in this case, the Expert-questline Amadron quest _does not_ sufficiently mention the E6-specific trades, only saying "perhaps you'll be surprised" (which is vague enough to be useless in this respect).
- The Amadron Survey Tools item is viewable in JEI, but is not very noticeable this way. Nothing about the Amadron Survey Kit in JEI describes at all what it is or does, except for if one were to search for Amadron Tablet recipes in JEI - particularly those using the survey tools or else Reinforced Chests - which I feel is not something that players would be particularly likely to do.
- Change the reward of the PNC-questline Amadron quest (or similar) to be 1x Amadron Survey Tools (or else part of their recipe, if a full Survey Tools would be too much as a reward). Giving one/part away as a reward would definitely make players more aware of them.
  - IMO - I think this would be a much more interesting reward than the current 1x Emerald Block. Sure, emeralds are useful, but they're never exactly hard to obtain - find a village and obtain a couple of stacks of paper, for instance - and even in Expert Mode, I've personally been _swimming_ in Emeralds since earlygame thanks to my Drygmy farm. Even disregarding their utility, emeralds are just not a very _interesting_ reward.

[ Thanks to generikb for his input on this, and to Enigmatica 6 contributor theboo for pointing out the existence of the Amadron Survey Tools to the both of us! ]

**Comment by MuteTiefling** [comment]
As it happens, a quest in the expert line was added to dev a few days ago to help improve discovery.

![image](https://user-images.githubusercontent.com/9543430/164909810-19e02a21-f714-43d0-8e05-785b8ecb462d.png)
![image](https://user-images.githubusercontent.com/9543430/164909801-38fc5baa-8628-45c2-936c-54671e3ebbd0.png)


As for what they do, however, I had hoped curiosity would be the driving factor. Since they're permanent trades in Amadron, they show up at the very top. Right along the Assembly Table programs and PCB Blueprint you must purchase for progression long before you can even craft the survey tools. The tooltips on the items say exactly what they're for:

![image](https://user-images.githubusercontent.com/9543430/164909592-53f44cac-3194-4d8d-ab15-ad128cd6a9b7.png)

That said, I'll see about adding some extra info to the tools themselves. I'm not sure to what degree that will help discoverability, however, as that still relies on the player accidentally noticing them in JEI. Checking uses there would also give an explicit list of what they're used for. 
![2022-04-23_10 13 47](https://user-images.githubusercontent.com/9543430/164909736-142feebf-ae52-428b-8be1-a95654b32270.png)

I like the idea of adding a free set of tools to the Prime Delivery quest, however. I think that's a good way to promote this.
