### ISSUE TITLE
Improve some Create recipes that can be done by Thermal machines

### ISSUE THREAD

**Issue by Steelux8** [EnigmaticaModpacks/Enigmatica6#4705]
### Describe your suggestion

There are a lot of early recipes that can be done either by Create or Thermal Series processing. For crafts like turning ingots to plates, for example, the Create setup is harder to put together, but it also runs much faster than what Thermal machines can do. In this case, I think the added difficulty has a good payoff, and automation isn't so difficult either way.

The issue I had is with other recipes, like making alloys. Thermal can do it in the Induction Smelter, which is one of the first machines this pack asks the player to make, and it can make many kinds of alloys just with the inputs and RF. The Create equivalent, however, is much harder to automate, and several alloys such as Enderium actually require a superheated Blaze Burner, which also needs Blaze Cake automation on top of everything else. With so many steps to automate basic alloys, there's a loss in processing speed, and the ratio of inputs to outputs is the same, despite Thermal being much easier to automate in general. 

The suggestion I'm making is to change these recipes, especially those that require superheating, to buff them in comparison to the Thermal recipes. More outputs, less inputs, something of the like.

### Why would you like this added/changed?

I think this change would give more incentive to work with Create, without forcing players into this kind of automation: they'll still be able to choose how they want to do things. I personally have spent many hours working on Create automation before moving onto IE and PnC, because I wanted an expert pack that made me automate those things before moving on to the usual machines and pipes. Buffing Create recipes will benefit the players dedicated to this, without punishing those that aren't.

**Comment by NielsPilgaard** [comment]
Interesting idea, we'll think it over :)
I'm slightly worried about dupes and feedback loops, but hopefully that can be avoided.

**Comment by Steelux8** [comment]
It would be easier to nerf the Thermal side, but also more impactful for the progression. I don't quite understand why enderium is obtainable so early with the Induction Smelter, and yet it needs superheating when done with Create.

**Comment by MuteTiefling** [comment]
Super heating isn't so that difficult to pull off either. Lava is infinite. Eggs are too. The worst part of them is probably the netherrack but a few minutes in the nether will get you enough to last for weeks of continuous use. 

Still, some of these can probably be improved. Steel is already a good example of where create is better, taking far less coke. Things like enderium and signalium could maybe have ratios adjusted, using fewer pearls and redstone. But that might mean removing them entirely from the centrifuge recipes to separate them. 

Create also processes much faster than thermal, especially when you consider how deep the integral components are. I'm actually thinking of shifting all my alloying over to that instead of my current thermal machines, as they're a bit of a bottle neck for me. You can easily get up to max speed in create long before you'll max out thermal. And it's generally much less expensive to run, with a single furnace engine running many machines for a small amount of fe/t, compared to thermal's cost.

**Comment by MuteTiefling** [comment]
The more I think on this, the more I fear it's just going to be a mess of finding all the dupe loops it'll invariably create. Create is faster early game, that's it's advantage.
