### ISSUE TITLE
Add more recipes to the automated iridescent altar

### ISSUE THREAD

**Issue by thatGuyCalledMax** [EnigmaticaModpacks/Enigmatica6#4722]
### Describe your suggestion

For more recipes to be added to the automated iridescent altar, such as the shifting star, and the irradiant stars (could do this by including the relevant constellation paper in the recipes, as well as making those craftable by the altar). Other crafts that could be added could include: the sink, parchment, astral relays, lightwells, runic altars, containment chalices and solar neutron activators

### Why would you like this added/changed?

So that you can automate all the crafts

**Comment by thatGuyCalledMax** [comment]
It mainly feels a bit incompleted since there's so few recipes for it, and im still going to have to craft manually on it a bunch more then i expected

**Comment by MuteTiefling** [comment]
The main goal of the automated version was to get the things you'll need for end game automated.

Can see about adding more though. Any other specific crafts? Do note I can't do the astral crafts that result in nbt transfer (lenses, for example)

**Comment by thatGuyCalledMax** [comment]
the only real ones i was looking at was stuff like lightwells/runic altars etc in case you wanted to mass produce them for larger scale automation, and the shifting stars, since they are needed for the laputian ingots (and the aevitas irradiant star since you need 4 for the tree of life controller, but understandable if that one is not possible, making 4 by hand isnt too hard)

**Comment by MuteTiefling** [comment]
Alright, taking a closer look at this now, I'd point out the following:

- Astral Relay: Can be batch crafted. And you'll almost certainly have as many as you'll ever need before the automated altar
- Lightwell: Similar situation. You can do these a stack at a time and are very likely to have everything you'd need well in advance of this multiblock
- Runic Altar: Considering you only ever need one of these, it seems like a strange one, again largely due to how late this would be available...
- Irradiant Stars: Tricky, since I can't require the constellation. Also only used for a couple one time crafts. Think I'll pass on this. 

- Shifting Star: Totally on board. Honestly though I had done it already
- Chalice: Seems niche, but batch crafting these kinda sucks because of the relay items. So that one seems fair to add
- Solar Neutron Activator: Same as chalice. However, due to the horologium requirement on the main craft, I'm leaning towards having it consume a horologium attuned crystal, if the recipe structure actually allows for that. If not, however, considering this is only used for Polonium in expert, and it processes fast enough that 2 can keep up with some pretty huge fission reactors... I'm not sure how needed this is.
