### ISSUE TITLE
[MM]Industrial Deuterium Plant Cannot be completed

### ISSUE THREAD

**Issue by Hatsune-Mku** [EnigmaticaModpacks/Enigmatica6#4784]
### Modpack Version

Masterful Machinery 0.1.60-B902

### Describe your issue.

Industrial Deuterium Plant can't be completed
I've experimented with both survival mode and creative mode 
It looks like the "immersiveengineering:tesla_coil" problem，The blueprint shows 4 but only 2 were actually placed Consume the same
![P%TMU_TUCT3U%6JHD N T4I](https://user-images.githubusercontent.com/41133549/167066520-27bdef33-0918-4442-b291-3ab17bc4aa65.png)

https://user-images.githubusercontent.com/41133549/167066923-84bd9572-c3b6-49fb-91ee-532d1f4b4d05.mp4

.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by AlphaP2712** [comment]
Did it need like water at base or something like that? 
![image](https://user-images.githubusercontent.com/74948675/167068166-acff3d1b-e1ba-4022-aeb2-3d9130d4d2ae.png)

**Comment by Hatsune-Mku** [comment]
Thank you very much for the reminder.English is not my native language,so I didn't read the task prompts carefully .I'll read the tips carefully afterwards，Thanks again for your answers  :)

**Comment by NielsPilgaard** [comment]
Did that resolve your issue?

**Comment by Quezler** [comment]
we fell into this pitfall as well, the way the pipes are positioned gives the impression that those need to be right above the water layer (since that's how you would normally use them in create, not having the input nozzle 3 blocks below the waterline), after manually checking the mm pattern i did notice the water requirement which caused me to circle back to reading the quest text and subsequent success in forming the multiblock, but it's a bit counter intuitive 🤔

**Comment by Hatsune-Mku** [comment]
The issue is resolved 
Thank you for your attention to this issue :)
