### ISSUE TITLE
Silky mod from Tinker's not working

### ISSUE THREAD

**Issue by ereinion** [EnigmaticaModpacks/Enigmatica6#4795]
### Modpack Version

1.1.2

### Describe your issue.

Applied silky enchantment to a pickaxe and a hammer. When trying to mine ores with either, the block breaking drops the standard chunks / raw drops instead of the block itself.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
Chunks are the silk touch drop, the difference is when mining gem ores such as diamonds you should now be getting the chunks instead of straight diamonds...

You can craft or stonecutter the chunks to ores if you want or use something like the enigmatic fortunizer to process the chunks directly with a fortune pick.
