### ISSUE TITLE
Cannot automate spirit of birthing

### ISSUE THREAD

**Issue by Ratlanta** [EnigmaticaModpacks/Enigmatica6#4806]
### Modpack Version

1.2.1

### Describe your issue.

I've tried every method of breeding animals to automate spirit of birthing and I have never gotten a single one to drop. This includes the feeding trough, router + activator/security upgrade, industrial foregoing animal feeder, and pedestal breeder. GiaruDK (E6E) said he tried the ars breeding ritual with no luck as well. If I manually breed the animals I get tons of them. The botanical mastery shards will require 2,000+ spirits of birthing so automation of this process is going to be important.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by TemperedFool** [comment]
ToAsgaard has a good example of automating the process in the following link:

https://www.youtube.com/watch?v=IXl0sjWzRuc

**Comment by theboo** [comment]
https://youtu.be/IXl0sjWzRuc?t=1308 timestamped link since it is 20 minutes in before they get to this part xD

**Comment by TemperedFool** [comment]
Boo you so generous!

On the other hand, I'd just suggest watching the whole video 😉

**Comment by Ratlanta** [comment]
Appreciate it but I replicated his exact setup (feeding trough + carrots breeding rabbits) and never saw a spirit of birthing drop. I'm about to test in a SP world but Giaru stated in discord that he was running into the same problem so I made this bug report.

**Comment by TemperedFool** [comment]
Alright, good info. Please let us know when you've tested in SP; will be good to know if you can replicate the issue there. 

To be clear, the area your setting up in has high aura?

**Comment by Ratlanta** [comment]
Aura is full on mp and sp.

![image](https://user-images.githubusercontent.com/59396659/167316494-a605a861-413f-459f-a8e1-ee949e9e977b.png)

 I just replicated results in single player as well. Zero spirits of birthing with ritual of fertility or feeding trough. As soon as I manually breed I get some spirits of birthing.

**Comment by MuteTiefling** [comment]
I've been using the ars ritual to get them without issue... Have you changed any gamerules?

**Comment by Ratlanta** [comment]
Nothing. I just spun up a fresh sp world and tried quark trough, ars fertility ritual and farming for blockheads. Tried cows, sheep and rabbits with zero spirits. Manual breeding works exactly as expected.

**Comment by theboo** [comment]
can confirm in SP the quark feeding trough does not seem to be giving birthing charms in 1.2.1... doing it by hand works just fine

**Comment by Darkere** [comment]
Code specifically checks the breeding was done by a player. https://github.com/Ellpeck/NaturesAura/blob/fb278bd76b82ec9e5f59a170510b91110259fc5a/src/main/java/de/ellpeck/naturesaura/items/ItemBirthSpirit.java#L24

**Comment by theboo** [comment]
makes sense, just weird it was working for people before since this hasnt been changed since Jan 2020

**Comment by Ratlanta** [comment]
I just loaded up my 1.1.2 instance and had the same results (no spirits unless manual feeding). Asgaard confirmed to me that he is on 1.2.1 and it's still working for him without issue. Apparently drones will work so I'm just going to set that up for now.

**Comment by Darkere** [comment]
drones, modular routers, ID should work

**Comment by Ratlanta** [comment]
Modular router with security upgrade does not work for me. It is feeding them and making babies but no spirits. Is there something else I would need to make it work? 

![image](https://user-images.githubusercontent.com/59396659/167317726-1d3ca5e9-ebcf-49dd-b573-7c041bd24627.png)

**Comment by MuteTiefling** [comment]
Something goofy is going on here, that's for sure. I've gone back and checked on my farm again and while it certainly _was_ working, it has since stopped.

**Comment by MuteTiefling** [comment]
Ok, so the issue here appears to be a combination of things:

1. Nature's Aura is expecting the animals to have a certain tag on them when breeding occurs. This allows it to track that the baby came from an actual breeding event, and not just the baby spawning in from something else.
2. None of the auto breeders I've tested actually set this tag, which should be considered a bug in those mods.
3. The tag is also not cleared after a breeding event, meaning if a player manually breeds animals first, NA will work fine with any other breeder that continues the process...

After speaking with Ell, there's really nothing they can do for this on their side. I don't think it's worth anyone's time to make bug reports with the 10 or so mods doing the breeding and hoping for any of them to fix it. And as it stands, while it's possible to automate currently, the way of doing this is... convoluted at best. Certainly not something easily discovered.

Now, personally, I don't want to change the recipes that use the spirits. I think it's a nice fun touch. So I'm proposing simply adding a recipe for them. For anyone that knows how to make the 'normal' way work, they get them for free. For anyone else, well, they'll have a little automation chain they can follow to get the process going.

**Comment by GiaruDK** [comment]
Drones work 100% i test )
![2022-05-10_16 31 32](https://user-images.githubusercontent.com/49821276/167685504-d3e64e55-9979-41f3-b095-bf5361942e0c.png)
![2022-05-10_16 31 25](https://user-images.githubusercontent.com/49821276/167685507-1f60b471-74db-4009-889e-d8f495397d73.png)

**Comment by StarskyXIII** [comment]
Majority people assign recipes of Runes only use JEI move item button without any tweaks.
![image](https://user-images.githubusercontent.com/71606873/167697291-1514231e-0bce-4791-a441-bb73f7cb680d.png)

But Runes in the Runic Altar Crafting will not be consumed.
So you can desigh a device to make rune cyclic in the Runic Altar Crafting system instead of Importing in RS.
https://drive.google.com/file/d/1s24gBoTh5SG3osE_roBFg8tauwqCpskh/view?usp=sharing

And then remove all the Runes which is the ingredient in the Runes' recipe.


Finally, you will notice it will not consume any Spirit of Birthing in your 50*Botanical Mastery Shards' Crafting.
https://user-images.githubusercontent.com/71606873/167699635-e33d735e-cbed-4740-b77f-f457123db8b8.mp4

**Comment by NielsPilgaard** [comment]
Somewhat unresolved, but also kinda fixed, gonna close this 😄

**Comment by XenonDB** [comment]
> But Runes in the Runic Altar Crafting will not be consumed. So you can desigh a device to make rune cyclic in the Runic Altar Crafting system instead of Importing in RS. https://drive.google.com/file/d/1s24gBoTh5SG3osE_roBFg8tauwqCpskh/view?usp=sharing


However, there's a bug with runes of mythic botany:
If you click altar manually, runes will not be returned:
![2022-05-11_14 31 03](https://user-images.githubusercontent.com/58476103/167786829-ff8e6924-097f-4dba-bb1d-ca69af206cda.png)

If you click altar by other automation way, runes will be returned:
[
![2022-05-11_14 29 05](https://user-images.githubusercontent.com/58476103/167786804-56f02cb6-b866-45eb-a368-717da4c49ab1.png)
](url)

**Comment by MuteTiefling** [comment]
I've done many manual runs crafts in my play through end never lost runes. So I think there's something more going on.

If you can replicate it reliably, please open a fresh issue for that.

**Comment by XenonDB** [comment]
> I've done many manual runs crafts in my play through end never lost runes. So I think there's something more going on.
> 
> If you can replicate it reliably, please open a fresh issue for that.

![image](https://user-images.githubusercontent.com/58476103/167831111-028963f9-17b3-4459-a5c1-31c08a5962c5.png)
Ok, forgot it.
Rune altar will not give runes back to creative player.
