### ISSUE TITLE
Nether portal having issues (killing players trying to go through/spitting them out thousands of blocks away from where they were supposed to be)

### ISSUE THREAD

**Issue by mctripleA** [EnigmaticaModpacks/Enigmatica6#4811]
### Modpack Version

v 1.w.1

### Describe your issue.

I updated the mod "BetterEndForge" the to "betterendreforked" for better performance, and in singleplayer the nether portal works as it should be, but on the server it will kill/almost kill players going to and from the nether, it may happen with other dimensions but Im unsure. it will also put anyone in creative into an infinite loop of entering and exiting the portal to teh point that you cant even dc from teh server, and I had to use the command prompt for the server tp force tp me out out of the portal 

heres where I got the reforked mod from https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files

### Crash Report

It hasnt crashed the server or clients

### Latest Log

<script src="https://gist.github.com/mctripleA/29375eee28fde773ef4e188c918c75cb.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

change the "betterEndForge" to "BetterEndReforked" https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked/files

client is also using Magensium 1.5 and "magnesium_extras-mc1.16.5_v1.3.1" if that matters, but a server member who wasn't using those still had the same issues

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
Enigmatica 6 has already switched to better end reforked as of version 1.2.0+ as seen here:
https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/changelogs/CHANGELOG.md#enigmatica-6--enigmatica-6-expert-v120

Usually these nether portal loops are caused by poor connection to the server/high ping scenarios, they can happen in vanilla worlds as well... I'm confused as to how you updated the mod when it is already in the pack tho... You are currently on pack version 1.2.1 correct?

**Comment by mctripleA** [comment]
sorry, I missed the version it was running, it is version 1.1.2, I have good ping as I just updated my internet to get better ping, and its still happening, I guess Ill see if I can update the pack on the server to see if that will change anything
