### ISSUE TITLE
start-server.bat/sh does not download mods (Replicated on Linux (.sh) and Windows (.batch))

### ISSUE THREAD

**Issue by Jakem721** [EnigmaticaModpacks/Enigmatica6#4873]
### Modpack Version

1.2.1

### Describe your issue.

I am attempting to set up a server for this modpack on the Google Cloud Platform. However, when I run the start-server.sh, it throws this error.
[ERROR] Error while trying to get URL from cursemeta for mod ModEntryRaw(projectID=309927, fileID=3725386)
For every mod it attempts to download, leading to the mod folder to be empty.
I also ran the start-server.bat file on my windows computer, in case it was an issue with me using Google Cloud. It throws the same error while using the batch file and has a similarly empty mods folder. 

I guess a solution for right now is manually installing every mod (with correct version number) myself, but that sounds like a pain.

### Latest Log

https://gist.github.com/Jakem721/c4292f5e8e51ab375fabb3d23dc5bc45

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
known issue, the old curseforge api is gone.

**Comment by Jakem721** [comment]
Ok. So is there a work around or do I just need to manually install every mod? I have not been able to find anything online.

**Comment by Quezler** [comment]
> Also, should I close this issue?

no, since its currently unfixed & everyone who runs into it will see this now instead of making their own issue :)

> Ok. So is there a work around

yes, i have made preparations (#4872) to fix it, once niller publishes a new release containing an updated `manifest.json` the already updated serverstarter 2.4.0 will be able to install the server just fine again.

i do have an updated manifest file myself, but pending a legality check for publicly posting cdn issues i won't post it here.

for now i can only suggest to install the client via the curseforge launcher, then copy those mods ([minus these](https://github.com/EnigmaticaModpacks/Enigmatica6/blob/12320118a0e760ad16f08fa43850296a9e3cd9ed/automation/remove-client-mods.ps1#L3) & [those](https://github.com/EnigmaticaModpacks/Enigmatica6/blob/12320118a0e760ad16f08fa43850296a9e3cd9ed/server_files/server-setup-config.yaml#L61)) over to the server instead of doing each of the several hundred by hand. not sure about the other steps the starter does tho 😅

**Comment by Jakem721** [comment]
Awesome, thanks!

**Comment by Jakem721** [comment]
Looking through #4872 into the pull requests, would the new manifest.json/server-starter4 releases be done through the alpha branch first and then the main release?

**Comment by Quezler** [comment]
based on the usual release pattern, it'll likely appear as an alpha client + server files release on curseforge when it does.

**Comment by NielsPilgaard** [comment]
Fixed in 1.3.0 :)
