### ISSUE TITLE
Halve time for crafting infused sunmetal blocks

### ISSUE THREAD

**Issue by BlackStone5677** [EnigmaticaModpacks/Enigmatica6#5215]
### Describe your suggestion

halve the crafting time of infused sunmetal blocks

### Why would you like this added/changed?

so it is more efficient to do blocks at a time rather than ingots at a time since you need quite a good amount of sunmetal for endgame and it's pretty slow currently

**Comment by MuteTiefling** [comment]
Sure thing. Not quite half, as their total aura cost needs to remain high for other reasons. The Altar itself can only import aura at 300 per tick max, so I've matched the crafting recipes to that rate and also reduced the cost of the blocks by the equivalent of 1 ingot. So crafting a block takes the aura/time of crafting 8 ingots instead of the full 9
