### ISSUE TITLE
Allow different types of Aura Generators for the "Aura Generation" quest

### ISSUE THREAD

**Issue by lolman360** [EnigmaticaModpacks/Enigmatica6#5342]
### Describe your suggestion

The quest for "Aura Generation" only accepts the Herbivorous Absorber and Shooting Mark. However, at the stage they are crafted, many other types of aura generator are available- the Offshoot Observer, Canopy Diminisher and others.

As such, the quest should be changed to allow different types of aura generators for completion.

### Why would you like this added/changed?

The Nature's Aura chapter has quests (with rewards) for many different types of aura generators, which may encourage players to make one of these first and then have to go back and make a different one solely for quest completion. This feels kind of counterproductive, and restricts player choice.

**Comment by MuteTiefling** [comment]
Those two are suggested in the Expert quests because they're simple to automate and meet the needs of Aura generation better than the others do at that point. 

The others you mentioned aren't as suitable and even have some common issues caused by other mod interactions. Remember, the quests are guiding you towards the big drop of the Masticator summon... you need to know how to generate a lot of Aura quickly. 

- Canopy Diminisher is very slow and sometimes has issues due to changes to oak trees implemented by other mods
- Offshoot Observer can be tricky to get a spawner working for it since other mods, in certain common configurations, cause spawners to only generate small slimes that cannot split and therefore generate no Aura
- Disentangler of Mortals, Reaper of Ender Heights, and Swamp Homi are all very slow
- Lingering Absorber would probably be viable, but potion automation at that point isn't exactly great.
- Firecracker Gaze wouldn't be available yet
